### ISSUE TITLE
Get request for individual user with invalid ID returns 500 Internal Server Error.

### ISSUE THREAD

**Issue by adguscott** [rawleyfowler/Humming-Bird-Microservice#1]
Get request for individual user with invalid ID returns 500 Internal Server Error instead of expected 404.

`500 Internal Server Error`

`Attempt to return outside of any Routine
in block at app.raku line 58 in method CALL-ME at /home/adam/.rakubrew/versions/moar-2023.02/share/perl6/site/sources/9D3C373E9E4B7F05E2DDDC70D1A9EA25C3B3A591 (Humming-Bird::Core) line 347 in sub dispatch-request at /home/adam/.rakubrew/versions/moar-2023.02/share/perl6/site/sources/9D3C373E9E4B7F05E2DDDC70D1A9EA25C3B3A591 (Humming-Bird::Core) line 516 in sub handle at /home/adam/.rakubrew/versions/moar-2023.02/share/perl6/site/sources/9D3C373E9E4B7F05E2DDDC70D1A9EA25C3B3A591 (Humming-Bird::Core) line 602 in block at /home/adam/.rakubrew/versions/moar-2023.02/share/perl6/site/sources/C3F6E4CCBD51F58D738B4E6EC268A75659BA67F0 (Humming-Bird::HTTPServer) line 43`

**Comment by rawleyfowler** [comment]
I'll look into this later today!

**Comment by rawleyfowler** [comment]
![image](https://user-images.githubusercontent.com/75388349/229944634-08868c91-ae37-4037-a9c3-7261fa8cccaf.png)


@adguscott What operating system, Raku version, and Humming-Bird version?

**Comment by adguscott** [comment]
OS: Ubuntu 22.04.2 LTS (WSL)
Raku: v2023.02.
Humming-Bird: ver<2.1.2>

Thanks for looking into this.

**Comment by rawleyfowler** [comment]
@adguscott Please pull down and try it again when you have a chance. I think it should work now, going from pointy blocks to subs, though I think on WSL there is a bug where pointy blocks aren't allowed returns for some reason.

**Comment by adguscott** [comment]
@rawleyfowler Works like a charm, thanks!
